# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
  - repo: https://github.com/FeryET/pre-commit-rust
    rev: v1.2.1
    hooks:
      - id: fmt
      - id: clippy
  - repo: https://github.com/bnjbvr/cargo-machete
    rev: v0.9.1
    hooks:
      - id: cargo-machete
  - repo: https://github.com/EmbarkStudios/cargo-deny
    rev: 0.19.0
    hooks:
      - id: cargo-deny
  - repo: local
    hooks:
      - id: npm-lint
        name: oxlint
        entry: npm
        args: ["run", "-w", "frontend", "lint", "--prefix", "vacs-client"]
        language: system
        files: '^vacs-client/frontend/.*\.(ts|tsx|js|jsx)$'
        pass_filenames: false
      - id: npm-typecheck
        name: TypeScript type check
        entry: npm
        args: ["run", "-w", "frontend", "typecheck", "--prefix", "vacs-client"]
        language: system
        files: '^vacs-client/frontend/.*\.(ts|tsx)$'
        pass_filenames: false
      - id: npm-format
        name: prettier
        entry: npm
        args: ["run", "format", "--prefix", "vacs-client"]
        language: system
        files: '^vacs-client/.*\.(ts|tsx|js|jsx|json|css|md)$'
        pass_filenames: false
