// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const isTauri: boolean = typeof (window as any).__TAURI_INTERNALS__ !== "undefined";

export type RemoteCommand =
    | "app_frontend_ready"
    | "app_open_folder"
    | "app_check_for_update"
    | "app_quit"
    | "app_update"
    | "app_platform_capabilities"
    | "app_set_always_on_top"
    | "app_set_fullscreen"
    | "app_reset_window_size"
    | "app_get_call_config"
    | "app_set_call_config"
    | "app_load_test_profile"
    | "app_unload_test_profile"
    | "app_get_client_page_settings"
    | "app_set_selected_client_page_config"
    | "app_load_extra_client_page_config"
    | "audio_get_hosts"
    | "audio_set_host"
    | "audio_get_devices"
    | "audio_set_device"
    | "audio_get_volumes"
    | "audio_set_volume"
    | "audio_play_ui_click"
    | "audio_start_input_level_meter"
    | "audio_stop_input_level_meter"
    | "audio_set_radio_prio"
    | "auth_open_oauth_url"
    | "auth_check_session"
    | "auth_logout"
    | "keybinds_get_transmit_config"
    | "keybinds_set_transmit_config"
    | "keybinds_get_keybinds_config"
    | "keybinds_set_binding"
    | "keybinds_get_radio_config"
    | "keybinds_set_radio_config"
    | "keybinds_get_radio_state"
    | "keybinds_get_external_binding"
    | "keybinds_open_system_shortcuts_settings"
    | "keybinds_reconnect_radio"
    | "remote_broadcast_store_sync"
    | "remote_get_session_state"
    | "remote_is_enabled"
    | "signaling_connect"
    | "signaling_disconnect"
    | "signaling_terminate"
    | "signaling_start_call"
    | "signaling_accept_call"
    | "signaling_end_call"
    | "signaling_get_ignored_clients"
    | "signaling_add_ignored_client"
    | "signaling_remove_ignored_client";

export type RemoteEvent =
    | "auth:authenticated"
    | "auth:unauthenticated"
    | "auth:error"
    | "error"
    | "radio:state"
    | "audio:radio-prio"
    | "audio:implicit-radio-prio"
    | "audio:input-level"
    | "audio:stop-input-level-meter"
    | "signaling:connected"
    | "signaling:reconnecting"
    | "signaling:disconnected"
    | "signaling:ambiguous-position"
    | "signaling:station-list"
    | "signaling:station-changes"
    | "signaling:client-list"
    | "signaling:client-connected"
    | "signaling:client-disconnected"
    | "signaling:client-not-found"
    | "signaling:call-invite"
    | "signaling:outgoing-call-accepted"
    | "signaling:call-end"
    | "signaling:call-reject"
    | "signaling:force-call-end"
    | "signaling:accept-incoming-call"
    | "signaling:add-incoming-to-call-list"
    | "signaling:update-call-list"
    | "signaling:test-profile"
    | "signaling:client-page-config"
    | "store:sync"
    | "webrtc:call-connected"
    | "webrtc:call-disconnected"
    | "webrtc:call-error"
    | "update:progress";

export type InvokeArgs = Record<string, unknown>;

export type EventCallback<T> = (event: {payload: T}) => void;

export type UnlistenFn = () => void;
