name: Release Please

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ref:
        description: "Target branch to prepare releases from (leave empty for default behavior)."
        required: false
        default: ""
        type: string

permissions: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      prs: ${{ steps.release.outputs.prs }}

    steps:
      - name: Generate GitHub token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: generate-token
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: vacs

      - uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        id: release
        with:
          target-branch: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref != '' && github.event.inputs.ref || github.ref_name }}
          token: ${{ steps.generate-token.outputs.token }}

  update-lockfiles:
    needs: release-please
    if: ${{ needs.release-please.outputs.prs }}
    strategy:
      fail-fast: false
      matrix:
        pr: ${{ fromJson(needs.release-please.outputs.prs) }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate GitHub token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: generate-token
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: vacs

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ matrix.pr.headBranchName }}
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}
          persist-credentials: false

      - name: Rust toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update

      - name: Cache cargo
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: "ubuntu-22.04-x86_64"

      - name: Update cargo workspace lockfile
        run: cargo update -w

      - name: Setup Node (LTS)
        if: contains(matrix.pr.headBranchName, 'vacs-client')
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: vacs-client/package-lock.json

      - name: Update npm workspace lockfile
        if: contains(matrix.pr.headBranchName, 'vacs-client')
        working-directory: vacs-client
        run: npm install --package-lock-only

      - name: Commit updated lockfiles
        uses: planetscale/ghcommit-action@25309d8005ac7c3bcd61d3fe19b69e0fe47dbdde # v0.2.20
        with:
          commit_message: "chore(lockfile): refresh cargo & npm lockfiles after version bumps"
          repo: ${{ github.repository }}
          branch: ${{ matrix.pr.headBranchName }}
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
